collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7437310519162565
color:
  saturation: 0.363905202364549
  brandStrength: 0.6526126214303076
  rhythmicContrast: 0.141487619606778
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.6394026770722121
layout_spectrum: 0.2615467
name: JC3D
